[workspace]
resolver = "3"
members = [
    "crates/game_client",
    "crates/game_server",
    "crates/gate_keeper",
    "crates/orchestrator",
    "crates/libs/game_sockets",
    "crates/spatial_server",
    "crates/broker",
    "crates/mock_spatial_auth_server",
    "crates/libs/broker_client",
    "crates/libs/not_games",
    "crates/libs/core_types",
    "crates/libs/broker_protocol",
    "crates/libs/game_message", "crates/libs/crate_test"]


#common dependencies
[workspace.dependencies]
game_sockets = { path = "crates/libs/game_sockets" }
broker_client = { path = "crates/libs/broker_client" }
not_games = { path = "crates/libs/not_games" }
core_types = { path = "crates/libs/core_types" }
broker_protocol = { path = "crates/libs/broker_protocol" }
game_message = { path = "crates/libs/game_message" }

# --- Moteurs et Réseau ---
bevy = "0.18.1"
tokio = "1.52.3"
rocket = { version = "0.5", features = ["json"] }
redis = { version = "1.2.1", features = ["tokio-comp"] }

# --- Utilitaires communs ---
anyhow = "1.0"
dotenv = "0.13.0"
uuid = { version = "1", features = ["v4"] }

# --- Sérialisation / Données ---
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
bitcode = "0.6.9"
bytes = "1.11.1"
