networks:
  mmo_network:
    driver: bridge
    name: mmo_network

services:
  game_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_game_server
    image: game-server
    container_name: game_server_template
    command: [ "echo", "✅ Image game-server compilée et prête pour l'orchestrateur !" ]
    restart: "no"
    networks:
      - mmo_network

  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mmo_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mmo_network

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_orchestrator
    image: orchestrator
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - "${ORCH_PORT}/udp"
    depends_on:
      redis:
        condition: service_started
      broker:
        condition: service_started
      game_server:
        condition: service_completed_successfully
    restart: always
    container_name: orchestrator
    networks:
      - mmo_network

  gate_keeper:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_gate_keeper
    image: gate-keeper
    env_file:
      - .env
    ports:
      - "${GATEKEEPER_PORT}:${GATEKEEPER_PORT}"
    depends_on:
      - orchestrator
      - db
    restart: always
    container_name: gate-keeper
    networks:
      - mmo_network

  dbgate:
    image: dbgate/dbgate
    ports:
      - "8081:3000"
    networks:
      - mmo_network
    environment:
      CONNECTIONS: con1,con2
      LABEL_con1: Postgres
      ENGINE_con1: postgres@dbgate-plugin-postgres
      SERVER_con1: db
      USER_con1: ${POSTGRES_USER}
      PASSWORD_con1: ${POSTGRES_PASSWORD}
      PORT_con1: 5432
      DATABASE_con1: ${POSTGRES_DB}
      LABEL_con2: Redis
      ENGINE_con2: redis@dbgate-plugin-redis
      SERVER_con2: redis
      PORT_con2: 6379
  broker:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_broker
    image: broker
    env_file:
      - .env
    ports:
      - "${BROKER_PRIVATE_PORT}:${BROKER_PRIVATE_PORT}/udp"
      - "${BROKER_PUBLIC_PORT}:${BROKER_PUBLIC_PORT}/udp"
    restart: always
    container_name: broker
    networks:
      - mmo_network
  spatial_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: final_spatial_server
    image: spatial-server
    env_file:
      - .env
    expose:
      - "${SPATIAL_PORT}/udp"
    restart: always
    depends_on:
      broker:
        condition: service_started
    container_name: spatial_server
    networks:
      - mmo_network
  #smock_spatial_auth_server:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  image: mock_spatial_auth_server
  #  env_file:
  #    - .env
  #  depends_on:
  #    - broker
  #  restart: always
  #  container_name: mock_spatial_auth_server
  #  networks:
  #    - mmo_network
  #  ports:
  #    - "3634:3634/udp"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgres_data:
  redis_data: