[package]
name = "gate_keeper"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
dotenv = { workspace = true }
rocket = { workspace = true }
shared_replication = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Spécifiques au Gatekeeper
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "macros"] }