[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
game_sockets = { workspace = true }
rustc-hash = { version = "2.1", default-features = false, features = ["std"] }
uuid = { workspace = true }
nohash-hasher = "0.2"
indexmap = "2.14.0"
broker_protocol = { workspace = true }
dashmap = "7.0.0-rc2"
crossbeam-channel = "0.5.15"