[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = { workspace = true }
dotenv = { workspace = true }
game_sockets = { workspace = true }
shared_replication = { workspace = true }
rustc-hash = { version = "2.1", default-features = false, features = ["std"] }
uuid = { workspace = true}
nohash-hasher = "0.2"