[package]
name = "game_server"
version = "0.1.0"
edition = "2024"

[dependencies]
# Héritées du workspace
dotenv = { workspace = true }
uuid = { workspace = true }
rustc-hash = { version = "2.1", default-features = false, features = ["std"] }

# Surcharge spécifique au serveur
bevy = { version = "0.18.1", default-features = false }
#bevy_rapier2d = {version = "0.33.0" }

broker_client = { workspace = true }
game_message = { workspace = true }
broker_protocol = { workspace = true }
core_types = { workspace = true }
bitcode = { workspace = true }



[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
