[package]
name = "orchestrator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true }
redis = { workspace = true }
anyhow = { workspace = true }
dotenv = { workspace = true }

# Spécifiques à l'Orchestrateur
bollard = "0.21"
futures-util = "0.3"
winapi = { version = "0.3", features = ["winerror", "minwindef", "winbase"] }
broker_client = { workspace = true }
not_games = { workspace = true }
game_message = { workspace = true }
broker_protocol = { workspace = true }