[package]
name = "game_client"
version = "0.1.0"
edition = "2024"

[dependencies]
# Héritées du workspace
shared_replication = { workspace = true }
game_sockets = { workspace = true }
bevy = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["rt", "net", "time"] }

# Spécifiques au client
bevy_egui = "0.39.1"
reqwest = { version = "0.12", features = ["json"] }
futures-lite = "2.6.1"
